server:
  port: 9003

spring:
  application:
    name: cloud-auth
  cloud:
    nacos:
      discovery:
        #配置Nacos地址
        server-addr: 49.234.63.142:8848
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
    #采样率值介于 0 到 1 之间，1 则表示全部采集
    probability: 1

# 配置actuator端点
management:
  endpoints:
    web:
      exposure:
        include: '*'